name = "botnet"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "BOTNET_KV"
id = "4fde3a045be140e28f581b9a3fe3f088"

[vars]
BOTNET_API_URL = "https://botnet.firefly-worker.workers.dev"
